version: '3.0'
services:

##############owe-hub-ui#####################
 service-owe-hub-ui:
   restart: always
   image: owe-hub-ui:v1
   networks:
     owe_net1:
       ipv4_address: 172.30.0.221
   ports:
     - "3000:3000"
   volumes:
     - /var/log/owe-ui/:/var/log/owe-ui/
   privileged: true

networks:
  owe_net1:
    driver: bridge
    name: docker_owe_net
    external: true
