FROM ubuntu:latest
LABEL maintainer="OWE_TEAM"

RUN apt-get update \
    && apt-get install -y lsof \
    net-tools \
    gdb \
    vim \
    psmisc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
