version: '3'

services:
  superset:
    build:
      context: ./superset
      dockerfile: dockerfile
    container_name: superset
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=yklHAGFCYCgTMBT
      - DATABASE_URL=postgresql+psycopg2://superset:superset@db:5433/superset
    ports:
      - '8088:8088'
    depends_on:
      - db
    # volumes:
    #   - ./superset-home:/home/superset
    #   - ./superset-config:/app/superset_config.py  # Mount your custom Superset config file if needed
    #   - ./superset-logs:/app/superset_logs  # Mount for persisting Superset logs
    networks:
      - superset-net

  db:
    image: postgres:13
    container_name: superset-db
    ports:
      - '5433:5432'  # Expose PostgreSQL on port 5433 on the host machine
    environment:
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_DB=superset
    volumes:
      -  /var/lib/superset/postgresql/data:/var/lib/postgresql/data  # Persist PostgreSQL data
    networks:
      - superset-net

networks:
  superset-net:
    driver: bridge

