#FROM timescale/timescaledb:latest-pg14
FROM postgres:latest

# Set environment variables
#ENV POSTGRES_DB owe_db
#ENV POSTGRES_USER OwePostgres
#ENV POSTGRES_PASSWORD OwePostgres

# Expose the PostgreSQL default port
EXPOSE 5432

COPY ./dbSchemas/DB_Create_Schema.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/rebate_items.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/rebate_type.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/timeline_sla.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/source.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/partners.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/states.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/rep_type.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/sale_type.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/v_user_details.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/tier.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/teams.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/appointment_setters.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/project_status.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/adder_type.csv /docker-entrypoint-initdb.d/

COPY ./dbSchemas/DB_ProcCreateNewUser.sql /docker-entrypoint-initdb.d/ 
COPY ./dbSchemas/DB_ProcCreateNewTeam.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateAptSetter.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcSmallSysSizeCalc.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCommisionTypeCalc.sql  /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateDealerPayExport.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewCommission.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewDealer.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewMarketingFees.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewVAdders.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewSaleType.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewTierLoanFee.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewDealerTier.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewPaymentSchedule.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewTimelineSla.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewPartner.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewState.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewLoanType.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateCommission.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateDealer.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateMarketingFee.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateVAdders.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateSaleType.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateTierLoanFee.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateDealerTier.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdatePaymentSchedule.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateTimelineSla.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateLoanType.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateCommissionArchive.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateDealerArchive.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateMarketingFeesArchive.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateVAddersArchive.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateSaleTypeArchive.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateTierLoanFeeArchive.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateDealerTierArchive.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdatePaymentScheduleArchive.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateTimelineSlaArchive.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateLoanTypeArchive.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewAutoAdder.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateAutoAdder.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcUpdateUser.sql /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/DB_Create_Schema.sql

