#FROM timescale/timescaledb:latest-pg14
FROM postgres:latest

# Set environment variables
#ENV POSTGRES_DB owe_db
#ENV POSTGRES_USER OwePostgres
#ENV POSTGRES_PASSWORD OwePostgres

# Expose the PostgreSQL default port
EXPOSE 5432

COPY ./dbSchemas/DB_Create_Schema.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/rebate_items.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/rebate_type.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/timeline_sla.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/source.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/partners.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/states.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/rep_type.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/sale_type.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/v_user_details.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/tier.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/teams.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/appointment_setters.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/project_status.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rawData/adder_type.csv /docker-entrypoint-initdb.d/

COPY ./dbSchemas/DB_ProcCreateNewUser.sql /docker-entrypoint-initdb.d/ 
COPY ./dbSchemas/DB_ProcCreateNewTeam.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateAptSetter.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcSmallSysSizeCalc.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCommisionTypeCalc.sql  /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateDealerPayExport.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewCommission.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewDealer.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewMarketingFees.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewVAdders.sql /docker-entrypoint-initdb.d/
COPY ./dbSchemas/DB_ProcCreateNewSaleType.sql /docker-entrypoint-initdb.d/

RUN chmod +x /docker-entrypoint-initdb.d/DB_Create_Schema.sql

