CREATE TABLE IF NOT EXISTS dealer_pay(
    home_owner TEXT,
    current_status TEXT,
    unique_id TEXT,
    dealer_code TEXT,
    today TIMESTAMP,
    amount float,
    sys_size float,
    rl float,
    contract_dol_dol float,
    loan_fee float,
    epc float,
    net_epc float,
    other_adders TEXT,
    credit TEXT,
    rep_1 TEXT,
    rep_2 TEXT,
    setter TEXT,
    draw_amt float,
    amt_paid float,
    balance float,
    st TEXT,
    contract_date TIMESTAMP
)