
/*

CREATE TABLE ar_data (
    partner text,
    installer text,
    type text,
    service text,
    home Owner text,
    address text,
    city text,
    state text,
    zip text,
    kw text,
    contract_date date,
    install_date date,
    current Status text,
    status_date date,
    contract text,
    owe_ar text,
    amt_paid text,
    current_due text,
    est_pipeline text
);

CREATE TABLE sales_ar_calc (
    serial_num text,
    dealer text,
    partner text,
    instl text,
    source text,
    type text,
    loan_type text,
    unique_id text,
    home_owner text,
    street_address text,
    city text,
    st text,
    zip text,
    email text,
    rep_1 text,
    rep_2 text,
    appt_setter text,
    sys_size text,
    kwh text,
    contract text,
    epc text,
    created text,
    wc text,
    pp text,
    ntp text,
    perm_sub text,
    perm_app text,
    ic_sub text,
    ic_app text,
    cancel text,
    inst_sys text,
    inst_elec text,
    fca text,
    pto text,
    status text,
    status_date text,
    rep_count text,
    per_rep_sales text,
    per_rep_kw text,
    red_line text,
    calc_date text,
    permit_pay text,
    permit_max text,
    install_pay text,
    pto_pay text,
    contract_calc text,
    epc_calc text,
    owe_ar text,
    gross_rev text,
    addr - ptr text,
    addr - auto text,
    loan_fee text,
    adjustment text,
    reconcile text,
    net_rev text,
    permit_pay text,
    install_pay text,
    pto_pay text,
    total_paid text,
    current_due text,
    balance text,
    dlr_rl text,
    dlr_tier text,
    dlr_mu text,
    dlr_mu_rpw text,
    owe_rl text,
    owe_rev text,
    owe_cost text,
    kw_profit text
);

CREATE TABLE ar_calc (
    dealer text,
    partner text,
    install text,
    source text,
    type text,
    loan_type text,
    unique_id text,
    home_owner text,
    street_address text,
    city text,
    st text,
    zip text,
    email text,
    rep_1 text,
    rep_2 text,
    appt_setter text,
    sys_size text,
    kwh text,
    contract text,
    epc text,
    created text,
    wc text,
    pp text,
    ntp text,
    perm_sub text,
    perm_app text,
    ic_sub text,
    ic_app text,
    cancel text,
    inst_sys text,
    inst_elec text,
    fca text,
    pto text,
    status text,
    status_date text,
    rep_count text,
    per_rep_sales text,
    per_rep_kw text,
    red_line text,
    calc_date text,
    permit_pay_m1 text,
    permit_max text,
    install_pay_m2 text,
    pto_pay_m3 text,
    contract_calc text,
    epc_calc text,
    owe_ar text,
    gross_rev text,
    addr - ptr text,
    addr - auto text,
    loan_fee text,
    adjust text,
    reconcile text,
    net_rev text,
    permit_pay text,
    install_pay text,
    pto_pay text,
    total_paid text,
    current_due text,
    balance text,
    dlr_rl text,
    dlr_tier text,
    dlr_mu text,
    dlr_mu_rpw text,
    owe_rl text,
    owe_rev text,
    owe_cost text,
    kw_profit text,
    total_profit text,
    fake_install text,
    epc_contract text,
    total_paid text
);

*/