export const routes={
    commissiondash:"/commission/dashboard",
    commissionrate:"/commission/config/commissionRate",
    dealerOverRoutes:"/commission/config/dealerOverrides",
    dealerTierRoutes:"/commission/config/dealerTier",
    marketingRoutes:"/commission/config/marketingFee",
    adderRoutes:"/commission/config/adderValidation",
    loanRoutes:"/commission/config/loanType",
    saleRoutes:"/commission/config/salesType",
    timelineRoutes:"/commission/config/timelineSla",
    paymentSchRoutes:"/commission/config/paymentSchedule",
    tierLoanFeeRoutes:"/commission/config/tierloanFee",
    autoadderRoutes:"/commission/config/autoAdder",
    loanFeeRoutes:"/commission/config/loanFeeAddr",
    rebetDataRoutes:"/commission/config/rebetData",
    referalDataRoutes:"/commission/config/referalData",
    dealerCreditRoutes:"/commission/config/dealerCredit",
    nonCommRoutes:"/commission/config/nonCommDlrPay",
    dlrOthRoutes:"/commission/config/dlrOthPay",
    // other routes
    reportRoutes:"/report" ,
    databaseRoutes:"/databaseController",
    projectRoutes:"/project",
    usermgtRoutes:"/userManagement",
    technicalSupportRoutes:"/technicalSupport",
    accountSettingRoutes:"/accountSetting",
    // databse manager routes 
    dbDashRoutes:"/dbManager/dashboard",
    dataTableRoutes:"/dbManager/dataTable",
    userActivityRoutes:"/dbManager/userActivity",
    webhookRoutes:"/dbManager/webhooks",
}