
export const ROUTES = {
  LOGIN: "/login",
  RESETPASSWORD: "/resetPassword",
  OTP: "/otp",
  COMMISSION_DASHBOARD: "/dashboard",
  REPPAY_DASHBOARD: "/reppay/dashboard",
  CONFIG_COMMISSION_RATE: "/commission/config/commissionRate",
  CONFIG_DEALER_OVER: "/commission/config/dealerOverrides",
  CONFIG_DEALER_TIER: "/commission/config/dealerTier",
  CONFIG_MARKETING: "/commission/config/marketingFee",
  CONFIG_ADDER: "/commission/config/adderValidation",
  CONFIG_LOAN: "/commission/config/loanType",
  CONFIG_SALE: "/commission/config/salesType",
  CONFIG_TIMELINE: "/commission/config/timelineSla",
  CONFIG_PAYMENT_SCHEDULE: "/commission/config/paymentSchedule",
  CONFIG_TIER_LOAN_FEE: "/commission/config/tierloanFee",
  CONFIG_AUTO_ADDER: "/commission/config/autoAdder",
  CONFIG_LOAN_FEE: "/commission/config/loanFeeAddr",
  CONFIG_REBET_DATA: "/commission/config/rebetData",
  CONFIG_REFERAL_DATA: "/commission/config/referalData",
  CONFIG_DEALER_CREDIT: "/commission/config/dealerCredit",
  CONFIG_NON_COMM_DLR_PAY: "/commission/config/nonCommDlrPay",
  CONFIG_DLE_OTH_PAY: "/commission/config/dlrOthPay",
  CONFIG_PAGE: "/commission/config",
  // other routes
  REPORT: "/report",
  DATABASE_CONTROLLER: "/databaseController",
  PROJECT: "/project",
  USER_MANAEMENT: "/userManagement",
  TECHNICAL_SUPPORT: "/technicalSupport",
  ACCOUNT_SETTING: "/accountSetting",
  // databse manager routes
  DB_MANAGER_DASHBOARD: "/dbManager/dashboard",
  DB_MANAGER_DATA_TABLE: "/dbManager/dataTable",
  DB_MANAGER_USER_ACTIVITY: "/dbManager/userActivity",
  DB_MANAGER_WEB_HOOKS: "/dbManager/webhooks",
};

