/**************************** OWE DB Schema ***********************************************************/
/* Test App End */
CREATE TABLE
    IF NOT EXISTS internal_ops_metrics_schema (
        item_id  bigint unique,
        unique_id varchar,
        customer text,
        prospect text,
        installer text,
        project_status text,
        puma_cat text,
        puma_cat_supervisor text,
        customer_last_contacted timestamp,
        source text,
        loan_type varchar,
        home_owner text,
        office text,
        system_size float,
        created_on timestamp,
        contract_date timestamp,
        prospect_working_date timestamp,
        hours_to_welcome_call text,
        ntp_working_date timestamp,
        ntp_date timestamp,
        credit_expiration_date timestamp,
        first_5_days_date timestamp,
        site_survey_scheduled_date timestamp,
        site_survey_rescheduled_date timestamp,
        site_survey_completed_date timestamp,
        cad_rejection_date timestamp,
        peee_rejection_date timestamp,
        cad_requested_date timestamp,
        cad_designer text,
        cad_ready timestamp,
        cad_complete_date timestamp,
        electrical_review_completion_date timestamp,
        cad_redline timestamp,
        cad_revision_requested_date timestamp,
        cad_revisions_completed timestamp,
        abcad_ready timestamp,
        abcad_completed timestamp,
        abcad_revised timestamp,
        abcad_revisions_completed timestamp,
        cad_review_date timestamp,
        cad_reviewer text,
        permit_redlined timestamp,
        peee_submitted_date timestamp,
        ab_permit_redlined timestamp,
        peee_complete_date timestamp,
        peee_redline_date timestamp,
        stamp_provider text,
        ahj text,
        solar_app_submission text,
        permit_created timestamp,
        permit_submitted_date timestamp,
        permit_expected_approval_date timestamp,
        permitting_specialist text,
        permit_re_submitted_date timestamp,
        permit_approved_date timestamp,
        fire_permit_created_date timestamp,
        fire_permit_submitted_date timestamp,
        fire_permit_approved_date timestamp,
        battery_permit_created_date timestamp,
        battery_permit_submitted_date timestamp,
        battery_permit_approved_date timestamp,
        electrical_permit_created_date timestamp,
        electrical_permit_submitted_date timestamp,
        electrical_permit_approved_date timestamp,
        pv_redlined_date timestamp,
        permit_turnaround_time text,
        ic_created_date timestamp,
        ic_submitted_date timestamp,
        ic_expected_approval_date timestamp,
        utility_specialist text,
        utility_company text,
        ic_re_submitted_date timestamp,
        ic_approved_date timestamp,
        ic_rejection_date timestamp,
        canceled_date timestamp,
        pv_install_created_date timestamp,
        pv_install_completed_date timestamp,
        electrical_submitted_date timestamp,
        electrical_approved_date timestamp,
        pto_created_date timestamp,
        pto_submitted_date timestamp,
        pto_resubmitted_date timestamp,
        pto_fail_date timestamp,
        pto_date timestamp,
        inverter_part_number text,
        module text,
        re_sync_slas text,
        within_sla text,
        outside_sla_current text,
        outside_sla_past text,
        metrics_last_updated text,
        adders_added_post_cad_r text,
        daily_sla_last_checked text,
        google_sheet_field_last_changed timestamp,
        hubspot_details text,
        google_sheets_update_required text,
        today text,
        today_date timestamp,
        field text,
        site_survey_complete_to_cad_review_complete text,
        sync_to_genesis_power_solutions text
    );

CREATE TABLE
    IF NOT EXISTS finance_metrics_schema (
        item_id  bigint unique,
        unique_id varchar,
        customer text,
        prospect text,
        dealer text,
        partner varchar,
        project_status text,
        puma_cat text,
        puma_cat_supervisor text,
        source text,
        loan_type varchar,
        finance_company text,
        home_owner text,
        office text,
        primary_sales_rep text,
        secondary_sales_rep text,
        system_size float,
        contract_total float,
        created_on timestamp,
        contract_date timestamp,
        ntp_working_date timestamp,
        ntp_date timestamp,
        credit_expiration_date timestamp,
        substantial_submitted text,
        substantial_redlined text,
        substantial_follow_up text,
        substantial_approved text,
        cancelled_date timestamp,
        active_date timestamp,
        pto_submitted_date timestamp,
        pto_date timestamp,
        module text,
        loan_type_transferred text
    );

CREATE TABLE
    IF NOT EXISTS sales_metrics_schema (
        item_id  bigint unique,
        unique_id varchar,
        customer text,
        prospect text,
        dealer text,
        account_executive text,
        partner varchar,
        state text,
        project_status text,
        puma_cat text,
        puma_cat_supervisor text,
        customer_last_contacted timestamp,
        source text,
        address text,
        loan_type varchar,
        finance_company text,
        finance_id text,
        home_owner text,
        office text,
        primary_sales_rep text,
        secondary_sales_rep text,
        system_size float,
        contract_total float,
        net_epc float,
        prospect_created_on timestamp,
        cad_created_on timestamp,
        wc_1 timestamp,
        wc_2 timestamp,
        contract_date timestamp,
        ntp_date timestamp,
        ntp_working_date timestamp,
        adders_total text,
        survey_2nd_completion_date timestamp,
        permit_submitted_date timestamp,
        permit_approved_date timestamp,
        credit_expiration_date timestamp,
        shaky_status_date timestamp,
        cancelled_date timestamp,
        active_date timestamp,
        pv_install_scheduled_date timestamp,
        pv_install_complete_1_2_date timestamp,
        pv_install_complete_2_3_date timestamp,
        pv_install_completed_date timestamp,
        pto_submitted_date timestamp,
        pto_date timestamp,
        module text,
        field text,
        permit_submittal_eta timestamp,
        install_eta timestamp,
        estimated_project_lifespan text,
        adjusted_project_lifespan text,
        project_lifespan_delta text,
        calculate_project_lifespan text,
        account_exec_added text,
        account_executive_calculation text,
        cancellation_reason text,
        setter text,
        leaderboard_name text
    );

CREATE TABLE
    IF NOT EXISTS field_ops_metrics_schema (
        item_id  bigint unique,
        unique_id varchar,
        customer text,
        prospect text,
        dealer text,
        project_status text,
        puma_cat text,
        puma_cat_supervisor text,
        home_owner text,
        office text,
        manager text,
        director text,
        system_size float,
        module text,
        module_count text,
        inverter text,
        inverter_count text,
        racking text,
        first_battery_type text,
        first_battery_qty text,
        second_battery_type text,
        second_battery_qty text,
        ev_charger_type text,
        contract_date timestamp,
        site_survey_scheduled_date timestamp,
        site_survey_rescheduled_date timestamp,
        site_survey_completed_date timestamp,
        surveyor_name text,
        permit_created timestamp,
        permit_submitted_date timestamp,
        pv_redlined_date timestamp,
        permit_redline_count text,
        permit_approved_date timestamp,
        shaky_status_date timestamp,
        cancelled_date timestamp,
        permit_resubmitted_date timestamp,
        ab_resubmitted_date timestamp,
        install_ready_date timestamp,
        pv_install_scheduled_date timestamp,
        install_rescheduled_date timestamp,
        install_eta timestamp,
        pv_install_completed_date timestamp,
        install_team text,
        install_manager text,
        rtr_request_date_and_time timestamp,
        rtr_approved_date timestamp,
        roof_type text,
        roofing_created_date timestamp,
        roofing_scheduled_date timestamp,
        roofing_completed_date timestamp,
        derate_created_date timestamp,
        derate_ready_date timestamp,
        derate_scheduled_date timestamp,
        derate_completed_date timestamp,
        derate_tech text,
        derate_reschedule_count text,
        mpu_created_date timestamp,
        mpu_ready_date timestamp,
        mpu_scheduled_date timestamp,
        mpu_complete_date timestamp,
        mpu_tech text,
        mpu_reschedule_count timestamp,
        battery_ready_date timestamp,
        battery_scheduled_date timestamp,
        battery_complete_date timestamp,
        initial_battery_tech text,
        sub_panel_module text,
        sub_panel_module_name text,
        der_type text,
        der_sow text,
        fin_scheduled_date timestamp,
        fin_pv_redlined_date timestamp,
        technician_assigned text,
        fin_rescheduled_date timestamp,
        fin_created_date timestamp,
        fin_fail_date timestamp,
        fin_pass_date timestamp,
        pto_date timestamp,
        service_created_date timestamp,
        service_pending_action_date timestamp,
        service_reschedule_count text,
        service_reschedule_date timestamp,
        service_scheduled_date timestamp,
        service_completion_date timestamp,
        re_sync_slas text,
        within_sla text,
        outside_sla_current text,
        outside_sla_past text,
        metrics_last_updated text,
        sync_to_genesis_power_solutions text
    );

CREATE TABLE
    IF NOT EXISTS next_steps_schema (
        item_id  bigint unique,
        customer text,
        unique_id varchar,
        project_age_days text,
        next_milestone_pv_pre_install text,
        next_step_pv_pre_install text,
        next_milestone_pv_pre_install_calc text,
        next_step_pv_pre_install_calc text,
        next_milestone_pv_pre_install_sync text,
        next_steps_pv_pre_install_sync text,
        pv_post_install text,
        pv_post_install_calc text,
        pv_post_install_sync text,
        electrical text,
        electrical_calc text,
        electrical_sync text,
        roofing text,
        roofing_calc text,
        roofing_sync text,
        temp_next_milestone_synced text
    );

CREATE VIEW
    consolidated_data_view AS
SELECT
    intOpsMetSchema.unique_id,
    intOpsMetSchema.installer,
    intOpsMetSchema.customer_last_contacted,
    intOpsMetSchema.home_owner,
    intOpsMetSchema.office,
    intOpsMetSchema.system_size,
    intOpsMetSchema.prospect_working_date,
    intOpsMetSchema.hours_to_welcome_call,
    intOpsMetSchema.first_5_days_date,
    intOpsMetSchema.site_survey_scheduled_date,
    intOpsMetSchema.site_survey_rescheduled_date,
    intOpsMetSchema.site_survey_completed_date,
    intOpsMetSchema.cad_rejection_date,
    intOpsMetSchema.peee_rejection_date,
    intOpsMetSchema.cad_requested_date,
    intOpsMetSchema.cad_designer,
    intOpsMetSchema.cad_ready,
    intOpsMetSchema.cad_complete_date,
    intOpsMetSchema.cad_redline,
    intOpsMetSchema.cad_revision_requested_date,
    intOpsMetSchema.cad_revisions_completed,
    intOpsMetSchema.abcad_ready,
    intOpsMetSchema.abcad_completed,
    intOpsMetSchema.abcad_revised,
    intOpsMetSchema.abcad_revisions_completed,
    intOpsMetSchema.cad_review_date,
    intOpsMetSchema.cad_reviewer,
    intOpsMetSchema.permit_redlined,
    intOpsMetSchema.peee_submitted_date,
    intOpsMetSchema.ab_permit_redlined,
    intOpsMetSchema.peee_complete_date,
    intOpsMetSchema.peee_redline_date,
    intOpsMetSchema.stamp_provider,
    intOpsMetSchema.ahj,
    intOpsMetSchema.permit_created,
    intOpsMetSchema.permit_submitted_date,
    intOpsMetSchema.permit_expected_approval_date,
    intOpsMetSchema.permitting_specialist,
    intOpsMetSchema.permit_re_submitted_date,
    intOpsMetSchema.permit_approved_date,
    intOpsMetSchema.fire_permit_created_date,
    intOpsMetSchema.fire_permit_submitted_date,
    intOpsMetSchema.fire_permit_approved_date,
    intOpsMetSchema.battery_permit_created_date,
    intOpsMetSchema.battery_permit_submitted_date,
    intOpsMetSchema.battery_permit_approved_date,
    intOpsMetSchema.electrical_permit_created_date,
    intOpsMetSchema.electrical_permit_submitted_date,
    intOpsMetSchema.electrical_permit_approved_date,
    intOpsMetSchema.pv_redlined_date,
    intOpsMetSchema.permit_turnaround_time,
    intOpsMetSchema.ic_created_date,
    intOpsMetSchema.ic_submitted_date,
    intOpsMetSchema.ic_expected_approval_date,
    intOpsMetSchema.utility_specialist,
    intOpsMetSchema.utility_company,
    intOpsMetSchema.ic_re_submitted_date,
    intOpsMetSchema.ic_approved_date,
    intOpsMetSchema.ic_rejection_date,
    intOpsMetSchema.canceled_date,
    intOpsMetSchema.pv_install_created_date,
    intOpsMetSchema.pv_install_completed_date,
    intOpsMetSchema.electrical_submitted_date,
    intOpsMetSchema.electrical_approved_date,
    intOpsMetSchema.pto_created_date,
    intOpsMetSchema.pto_submitted_date,
    intOpsMetSchema.pto_fail_date,
    intOpsMetSchema.pto_date,
    intOpsMetSchema.inverter_part_number,
    intOpsMetSchema.module,
    salMetSchema.customer,
    salMetSchema.prospect,
    salMetSchema.project_status,
    salMetSchema.puma_cat,
    salMetSchema.puma_cat_supervisor,
    salMetSchema.source,
    salMetSchema.loan_type,
    salMetSchema.contract_date,
    salMetSchema.ntp_working_date,
    salMetSchema.ntp_date,
    salMetSchema.credit_expiration_date,
    salMetSchema.shaky_status_date,
    salMetSchema.cancelled_date,
    salMetSchema.pv_install_scheduled_date,
    salMetSchema.install_eta,
    salMetSchema.dealer,
    salMetSchema.account_executive,
    salMetSchema.partner,
    salMetSchema.state,
    salMetSchema.address,
    salMetSchema.finance_company,
    salMetSchema.finance_id,
    salMetSchema.primary_sales_rep,
    salMetSchema.secondary_sales_rep,
    salMetSchema.contract_total,
    salMetSchema.net_epc,
    salMetSchema.prospect_created_on,
    salMetSchema.wc_1,
    salMetSchema.wc_2,
    salMetSchema.active_date,
    salMetSchema.permit_submittal_eta,
    salMetSchema.estimated_project_lifespan,
    salMetSchema.adjusted_project_lifespan,
    salMetSchema.project_lifespan_delta,
    fieldOpsSchema.director,
    fieldOpsSchema.surveyor_name,
    fieldOpsSchema.permit_redline_count,
    fieldOpsSchema.permit_resubmitted_date,
    fieldOpsSchema.ab_resubmitted_date,
    fieldOpsSchema.install_ready_date,
    fieldOpsSchema.install_rescheduled_date,
    fieldOpsSchema.install_team,
    fieldOpsSchema.install_manager,
    fieldOpsSchema.rtr_request_date_and_time,
    fieldOpsSchema.rtr_approved_date,
    fieldOpsSchema.roofing_created_date,
    fieldOpsSchema.roofing_scheduled_date,
    fieldOpsSchema.roofing_completed_date,
    fieldOpsSchema.derate_ready_date,
    fieldOpsSchema.derate_scheduled_date,
    fieldOpsSchema.derate_completed_date,
    fieldOpsSchema.derate_tech,
    fieldOpsSchema.mpu_ready_date,
    fieldOpsSchema.mpu_scheduled_date,
    fieldOpsSchema.mpu_tech,
    fieldOpsSchema.battery_ready_date,
    fieldOpsSchema.battery_scheduled_date,
    fieldOpsSchema.battery_complete_date,
    fieldOpsSchema.initial_battery_tech,
    fieldOpsSchema.fin_scheduled_date,
    fieldOpsSchema.technician_assigned,
    fieldOpsSchema.fin_rescheduled_date,
    fieldOpsSchema.fin_created_date,
    fieldOpsSchema.fin_fail_date,
    fieldOpsSchema.fin_pass_date,
    fieldOpsSchema.service_created_date,
    fieldOpsSchema.service_pending_action_date,
    fieldOpsSchema.service_reschedule_count,
    fieldOpsSchema.service_reschedule_date,
    fieldOpsSchema.service_scheduled_date,
    fieldOpsSchema.service_completion_date,
    fieldOpsSchema.mpu_complete_date,
    fieldOpsSchema.fin_pv_redlined_date,
    salMetSchema.survey_2nd_completion_date,
    salMetSchema.pv_install_complete_1_2_date,
    salMetSchema.pv_install_complete_2_3_date,
    fieldOpsSchema.derate_created_date,
    fieldOpsSchema.mpu_created_date,
    (intOpsMetSchema.system_size * 1000)/ salMetSchema.contract_total AS epc
FROM
    (
        SELECT
            unique_id,
            installer,
            customer_last_contacted,
            home_owner,
            office,
            system_size,
            prospect_working_date,
            hours_to_welcome_call,
            first_5_days_date,
            site_survey_scheduled_date,
            site_survey_rescheduled_date,
            site_survey_completed_date,
            cad_rejection_date,
            peee_rejection_date,
            cad_requested_date,
            cad_designer,
            cad_ready,
            cad_complete_date,
            cad_redline,
            cad_revision_requested_date,
            cad_revisions_completed,
            abcad_ready,
            abcad_completed,
            abcad_revised,
            abcad_revisions_completed,
            cad_review_date,
            cad_reviewer,
            permit_redlined,
            peee_submitted_date,
            ab_permit_redlined,
            peee_complete_date,
            peee_redline_date,
            stamp_provider,
            ahj,
            permit_created,
            permit_submitted_date,
            permit_expected_approval_date,
            permitting_specialist,
            permit_re_submitted_date,
            permit_approved_date,
            fire_permit_created_date,
            fire_permit_submitted_date,
            fire_permit_approved_date,
            battery_permit_created_date,
            battery_permit_submitted_date,
            battery_permit_approved_date,
            electrical_permit_created_date,
            electrical_permit_submitted_date,
            electrical_permit_approved_date,
            pv_redlined_date,
            permit_turnaround_time,
            ic_created_date,
            ic_submitted_date,
            ic_expected_approval_date,
            utility_specialist,
            utility_company,
            ic_re_submitted_date,
            ic_approved_date,
            ic_rejection_date,
            canceled_date,
            pv_install_created_date,
            pv_install_completed_date,
            electrical_submitted_date,
            electrical_approved_date,
            pto_created_date,
            pto_submitted_date,
            pto_fail_date,
            pto_date,
            inverter_part_number,
            module
        FROM
            internal_ops_metrics_schema
        WHERE
            unique_id IS NOT NULL
            AND unique_id <> ''
    ) intOpsMetSchema
    JOIN sales_metrics_schema salMetSchema ON intOpsMetSchema.unique_id = salMetSchema.unique_id
    JOIN field_ops_metrics_schema fieldOpsSchema ON intOpsMetSchema.unique_id = fieldOpsSchema.unique_id;

CREATE VIEW ops_analysis_timelines_view AS
SELECT
    intOpsMetSchema.unique_id,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.ntp_date - intOpsMetSchema.site_survey_completed_date)) / 86400.0, 2)) AS survey_to_ntp,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.cancelled_date - intOpsMetSchema.site_survey_completed_date)) / 86400.0, 2)) AS survey_to_cancel,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.pv_install_completed_date - intOpsMetSchema.site_survey_completed_date)) / 86400.0, 2)) AS survey_to_install,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.pto_date - intOpsMetSchema.site_survey_completed_date)) / 86400.0, 2)) AS survey_to_pto,
    ABS(ROUND(EXTRACT(epoch FROM (intOpsMetSchema.site_survey_completed_date - intOpsMetSchema.site_survey_scheduled_date)) / 86400.0, 2)) AS survey_scheduled_to_survey_completed,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.contract_date - intOpsMetSchema.site_survey_completed_date)) / 86400.0, 2)) AS sales_to_survey,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.ntp_date - salMetSchema.contract_date)) / 86400.0, 2)) AS sales_to_ntp,
    ABS(ROUND(EXTRACT(epoch FROM (intOpsMetSchema.cad_complete_date - salMetSchema.contract_date)) / 86400.0, 2)) AS sale_to_cad_completed,
    ABS(ROUND(EXTRACT(epoch FROM (intOpsMetSchema.ic_submitted_date - salMetSchema.contract_date)) / 86400.0, 2)) AS sale_to_ic_submission,
    ABS(ROUND(EXTRACT(epoch FROM (intOpsMetSchema.permit_submitted_date - salMetSchema.contract_date)) / 86400.0, 2)) AS sale_to_permit_submission,
    ABS(ROUND(EXTRACT(epoch FROM (intOpsMetSchema.ic_approved_date - salMetSchema.contract_date)) / 86400.0, 2)) AS sale_to_ic_approved,
    ABS(ROUND(EXTRACT(epoch FROM (intOpsMetSchema.permit_approved_date - salMetSchema.contract_date)) / 86400.0, 2)) AS sale_to_permit_approved,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.pv_install_completed_date - salMetSchema.contract_date)) / 86400.0, 2)) AS sales_to_install,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.cancelled_date - salMetSchema.contract_date)) / 86400.0, 2)) AS sales_to_cancel,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.pto_date - salMetSchema.contract_date)) / 86400.0, 2)) AS sales_to_pto,
    ABS(ROUND(EXTRACT(epoch FROM (intOpsMetSchema.cad_complete_date - intOpsMetSchema.cad_requested_date)) / 86400.0, 2)) AS cad_requested_to_cad_completed,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.permit_submitted_date - intOpsMetSchema.cad_requested_date)) / 86400.0, 2)) AS cad_complete_to_permit_submitted,
    ABS(ROUND(EXTRACT(epoch FROM (intOpsMetSchema.electrical_permit_approved_date - intOpsMetSchema.cad_requested_date)) / 86400.0, 2)) AS cad_completed_to_electrical_permit_approved,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.cancelled_date - salMetSchema.ntp_date)) / 86400.0, 2)) AS ntp_to_cancel,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.pv_install_completed_date - salMetSchema.ntp_date)) / 86400.0, 2)) AS ntp_to_install,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.pto_date - salMetSchema.ntp_date)) / 86400.0, 2)) AS ntp_to_pto,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.pv_install_completed_date - intOpsMetSchema.permit_approved_date)) / 86400.0, 2)) AS pv_permit_approved_to_install_complete,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.cancelled_date - salMetSchema.pv_install_completed_date)) / 86400.0, 2)) AS install_to_cancel,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.pto_date - salMetSchema.pv_install_completed_date)) / 86400.0, 2)) AS install_to_pto,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.pv_install_completed_date - fieldOpsSchema.pv_install_scheduled_date)) / 86400.0, 2)) AS install_scheduled_to_install_complete,
    ABS(ROUND(EXTRACT(epoch FROM (fieldOpsSchema.fin_pass_date - salMetSchema.pv_install_completed_date)) / 86400.0, 2)) AS install_to_fin,
    ABS(ROUND(EXTRACT(epoch FROM (fieldOpsSchema.fin_scheduled_date - salMetSchema.pv_install_completed_date)) / 86400.0, 2)) AS install_to_fin_submitted,
    ABS(ROUND(EXTRACT(epoch FROM (intOpsMetSchema.pto_submitted_date - salMetSchema.pv_install_completed_date)) / 86400.0, 2)) AS install_to_pto_submitted,
    ABS(ROUND(EXTRACT(epoch FROM (salMetSchema.pto_date - fieldOpsSchema.rtr_approved_date)) / 86400.0, 2)) AS rtr_pass_pto_pass,
    ABS(ROUND(EXTRACT(epoch FROM (fieldOpsSchema.fin_fail_date - fieldOpsSchema.rtr_approved_date)) / 86400.0, 2)) AS rtr_pass_fin_fail,
    ABS(ROUND(EXTRACT(epoch FROM (intOpsMetSchema.pto_fail_date - fieldOpsSchema.rtr_approved_date)) / 86400.0, 2)) AS rtr_pass_pto_fail,
    ABS(ROUND(EXTRACT(epoch FROM (fieldOpsSchema.rtr_approved_date - fieldOpsSchema.rtr_request_date_and_time)) / 86400.0, 2)) AS rtr_speed,
    ABS(ROUND(EXTRACT(epoch FROM (fieldOpsSchema.service_completion_date - fieldOpsSchema.service_created_date)) / 86400.0, 2)) AS service_open_to_service_completed,
    ABS(ROUND(EXTRACT(epoch FROM (fieldOpsSchema.mpu_complete_date - intOpsMetSchema.cad_complete_date)) / 86400.0, 2)) AS cad_to_mpu_completed,
    ABS(ROUND(EXTRACT(epoch FROM (fieldOpsSchema.mpu_complete_date - fieldOpsSchema.mpu_scheduled_date)) / 86400.0, 2)) AS mpu_scheduled_to_mpu_completed,
    ABS(ROUND(EXTRACT(epoch FROM (fieldOpsSchema.derate_completed_date - intOpsMetSchema.cad_complete_date)) / 86400.0, 2)) AS cad_completed_to_derate_completed,
    ABS(ROUND(EXTRACT(epoch FROM (fieldOpsSchema.derate_completed_date - fieldOpsSchema.derate_completed_date)) / 86400.0, 2)) AS derate_scheduled_to_derate_completed,
    ABS(ROUND(EXTRACT(epoch FROM (fieldOpsSchema.battery_complete_date - fieldOpsSchema.battery_scheduled_date)) / 86400.0, 2)) AS battery_scheduled_to_battery_completed
    FROM
    (
        SELECT
            unique_id,
            site_survey_scheduled_date,
            site_survey_completed_date,
			cad_complete_date,
			ic_submitted_date,
			permit_submitted_date,
			ic_approved_date,
			permit_approved_date,
			cad_requested_date,
			pto_fail_date,
            electrical_permit_approved_date,
            pto_submitted_date
        FROM
            internal_ops_metrics_schema
        WHERE
            unique_id IS NOT NULL
            AND unique_id <> ''
    ) intOpsMetSchema
JOIN sales_metrics_schema salMetSchema ON intOpsMetSchema.unique_id = salMetSchema.unique_id
JOIN field_ops_metrics_schema fieldOpsSchema ON intOpsMetSchema.unique_id = fieldOpsSchema.unique_id;