#FROM timescale/timescaledb:latest-pg14
FROM postgres:latest

# Set environment variables
#ENV POSTGRES_DB owe_db
#ENV POSTGRES_USER OwePostgres
#ENV POSTGRES_PASSWORD OwePostgres

# Expose the PostgreSQL default port
EXPOSE 5432

COPY ./dbSchemas/DB_Create_Schema.sql /docker-entrypoint-initdb.d/

COPY ./dbSchemas/rebate_items.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rebate_type.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/timeline_sla.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/source.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/partners.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/v_dealer.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/states.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/rep_type.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/sale_type.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/v_reps.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/tier.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/teams.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/appointment_setters.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/project_status.csv /docker-entrypoint-initdb.d/
COPY ./dbSchemas/adder_type.csv /docker-entrypoint-initdb.d/
 
RUN chmod +x /docker-entrypoint-initdb.d/DB_Create_Schema.sql

