#FROM timescale/timescaledb:latest-pg14
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB owe_db
ENV POSTGRES_USER OwePostgres
ENV POSTGRES_PASSWORD OwePostgres

# Expose the PostgreSQL default port
EXPOSE 5432


COPY ./dbSchemas/DB_Create_Schema.sql /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/DB_Create_Schema.sql

