export default [
  {
    name: 'unique_id',
    displayName: 'Unique ID',
    type: 'string',
    isCheckbox: true,
  },
  {
    name: 'rep1',
    displayName: 'Rep 1',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'home_owner',
    displayName: 'Home Owner',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'contract_date',
    displayName: 'Contract Date',
    type: 'date',
    isCheckbox: false,
  },
  { name: 'amount', displayName: 'Amount', type: 'number', isCheckbox: false },
  {
    name: 'amt_paid',
    displayName: 'Amount Paid',
    type: 'number',
    isCheckbox: false,
  },
  {
    name: 'balance',
    displayName: 'Balance',
    type: 'number',
    isCheckbox: false,
  },
  { name: 'credit', displayName: 'Credit', type: 'number', isCheckbox: false },
  { name: 'epc', displayName: 'EPC', type: 'number', isCheckbox: false },
  {
    name: 'net_epc',
    displayName: 'NET EPC',
    type: 'number',
    isCheckbox: false,
  },
  {
    name: 'net_rev',
    displayName: 'NET REV',
    type: 'number',
    isCheckbox: false,
  },
  {
    name: 'current_status',
    displayName: 'Current Status',
    type: 'string',
    isCheckbox: false,
  },
  { name: 'dba', displayName: 'DBA', type: 'string', isCheckbox: false },
  {
    name: 'status_date',
    displayName: 'Status Date',
    type: 'date',
    isCheckbox: false,
  },
  {
    name: 'sys_size',
    displayName: 'Sys Size',
    type: 'number',
    isCheckbox: false,
  },
  {
    name: 'dealer_code',
    displayName: 'Dealer Code',
    type: 'number',
    isCheckbox: false,
  },
  {
    name: 'type',
    displayName: 'Type',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'today',
    displayName: 'Today',
    type: 'number',
    isCheckbox: false,
  },
  {
    name: 'contract',
    displayName: 'Contract $$',
    type: 'number',
    isCheckbox: false,
  },
  {
    name: 'setter',
    displayName: 'Setter',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'rep_pay',
    displayName: 'Rep Pay',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'st',
    displayName: 'ST',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'sub_total',
    displayName: 'Sub Total',
    type: 'number',
    isCheckbox: false,
  },
  {
    name: 'loan_fee',
    displayName: 'Loan Fee',
    type: 'number',
    isCheckbox: false,
  },
  {
    name: 'draw_amt',
    displayName: 'Draw Amt',
    type: 'number',
    isCheckbox: false,
  },
  { name: 'rl', displayName: 'RL', type: 'number', isCheckbox: false },
  {
    name: 'OtherAdders',
    displayName: 'Other Adders',
    type: 'number',
    isCheckbox: false,
  },
  { name: 'rep2', displayName: 'Rep 2', type: 'string', isCheckbox: false },
  { name: 'help', displayName: 'Help', type: 'string', isCheckbox: false },
];
