name: Deploy to Staging Server

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'dev'  # Default value if not specified
  #push:
  #branches:
  #   - dev  # Deploy when code is pushed to the dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.OWEHUB_STAGING_SSH_PRIVATE_KEY }}

    - name: Checkout latest dev branch
      run: |
        ssh -p ${{ secrets.OWEHUB_STAGING_SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.OWEHUB_STAGING_USERNAME }}@${{ secrets.OWEHUB_STAGING_SERVER }} << 'EOF'
        cd /home/ubuntu/deploy/OweAppPlatform
        git clean -fd
        git checkout .
        git fetch --all
        git checkout dev
        git pull origin dev

    - name: Deploying GUI
      run: |
        ssh -p ${{ secrets.OWEHUB_STAGING_SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.OWEHUB_STAGING_USERNAME }}@${{ secrets.OWEHUB_STAGING_SERVER }} << 'EOF'
        cd /home/ubuntu/deploy/OweAppPlatform/owehub/scripts/
        cp ../gui/.env.staging ../gui/.env
        rm -rf ../gui/.env.staging ../gui/.env.production
        ./deploy-owehub.sh gui
        git clean -fd ../../
        git checkout ../../
        
    - name: Deploying Backend
      run: |
        ssh -p ${{ secrets.OWEHUB_STAGING_SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.OWEHUB_STAGING_USERNAME }}@${{ secrets.OWEHUB_STAGING_SERVER }} << 'EOF'
        cd /home/ubuntu/deploy/OweAppPlatform/owehub/scripts/
        ./deploy-owehub.sh backend

    - name: Migrating Databse
      run: |
        ssh -p ${{ secrets.OWEHUB_STAGING_SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.OWEHUB_STAGING_USERNAME }}@${{ secrets.OWEHUB_STAGING_SERVER }} << 'EOF'
        cd /home/ubuntu/deploy/OweAppPlatform/owehub/scripts/
        ./deploy-owehub.sh migrate_db
    
        EOF
