name: Deploy to Staging Server

on:
  push:
    branches:
      - dev  # Deploy when code is pushed to the dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.OWEHUB_STAGING_SSH_PRIVATE_KEY }}

          #- name: Copy files to server
          #run: |
          #scp -P ${{ secrets.OWEHUB_STAGING_SSH_PORT }} -o StrictHostKeyChecking=no -r ./* ${{ secrets.OWEHUB_STAGING_USERNAME }}@${{ secrets.OWEHUB_STAGING_SERVER }}:/home/ubuntu/github

    - name: SSH on Staging Server
      run: |
        ssh -p ${{ secrets.OWEHUB_STAGING_SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.OWEHUB_STAGING_USERNAME }}@${{ secrets.OWEHUB_STAGING_SERVER }} << 'EOF'

    - name: Checkout latest dev branch
      run: |
        cd /home/ubuntu/deploy/OweAppPlatform
        git clean -fd
        git checkout .
        git fetch --all
        git checkout dev
        git pull origin dev

    - name: Deploying GUI
      run: |
        cd owehub/scripts/
        cp ../gui/.env.staging ../gui/.env
        ./deploy-owehub.sh gui
        rm ../gui/.env
        
    - name: Migrating Databse
      run: |
        ./deploy-owehub.sh migrate_db
    
    - name: Deploying Backend
      run: |
        ./deploy-owehub.sh backend
    
        EOF
