name: Deploy to Production Server

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'main'  # Default value if not specified
  #push:
  #branches:
  #    - main  # Deploy when code is pushed to the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.OWEHUB_PRODUCTION_SSH_PRIVATE_KEY }}

          #- name: Copy files to server
          #run: |
          #scp -P ${{ secrets.OWEHUB_PRODUCTION_SSH_PORT }} -o StrictHostKeyChecking=no -r ./* ${{ secrets.OWEHUB_PRODUCTION_USERNAME }}@${{ secrets.OWEHUB_PRODUCTION_SERVER }}:/home/ubuntu/github

          #    - name: SSH on Production Server
          #run: |
          #ssh -p ${{ secrets.OWEHUB_PRODUCTION_SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.OWEHUB_PRODUCTION_USERNAME }}@${{ secrets.OWEHUB_PRODUCTION_SERVER }} << 'EOF'

    - name: Checkout latest main branch
      run: |
        ssh -p ${{ secrets.OWEHUB_PRODUCTION_SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.OWEHUB_PRODUCTION_USERNAME }}@${{ secrets.OWEHUB_PRODUCTION_SERVER }} << 'EOF'
        cd /home/ubuntu/deploy/OweAppPlatform
        git clean -fd
        git checkout .
        git fetch --all
        git checkout main
        git pull origin main
        
    - name: Deploying GUI
      run: |
        ssh -p ${{ secrets.OWEHUB_PRODUCTION_SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.OWEHUB_PRODUCTION_USERNAME }}@${{ secrets.OWEHUB_PRODUCTION_SERVER }} << 'EOF'
        cd /home/ubuntu/deploy/OweAppPlatform/owehub/scripts/
        cp ../gui/.env.production ../gui/.env
        rm -rf ../gui/.env.staging ../gui/.env.production
        ./deploy-owehub.sh gui
        git clean -fd ../../
        git checkout ../../

    - name: Deploying Backend
      run: |
        ssh -p ${{ secrets.OWEHUB_PRODUCTION_SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.OWEHUB_PRODUCTION_USERNAME }}@${{ secrets.OWEHUB_PRODUCTION_SERVER }} << 'EOF'
        cd /home/ubuntu/deploy/OweAppPlatform/owehub/scripts/
        ./deploy-owehub.sh backend

    - name: Migrating Databse
      run: |
        ssh -p ${{ secrets.OWEHUB_PRODUCTION_SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.OWEHUB_PRODUCTION_USERNAME }}@${{ secrets.OWEHUB_PRODUCTION_SERVER }} << 'EOF'
        cd /home/ubuntu/deploy/OweAppPlatform/owehub/scripts/
        ./deploy-owehub.sh migrate_db

        EOF
