export default [
  {
    name: 'unique_id',
    displayName: 'Unique ID',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'home_owner',
    displayName: 'Home Owner',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'finance_company',
    displayName: 'Financer',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'source_type',
    displayName: 'Source',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'current_status',
    displayName: 'Type',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'loan_type',
    displayName: 'Loan Type',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'street_address',
    displayName: 'Street Address',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'city',
    displayName: 'City',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'state',
    displayName: 'ST',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'zip_code',
    displayName: 'ZIP',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'email',
    displayName: 'Email',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'phone_number',
    displayName: 'Phone Number',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'rep_1',
    displayName: 'Rep 1',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'appt_setter',
    displayName: 'Appt Setter',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'system_size',
    displayName: 'Sys. Size',
    type: 'string',
    isCheckbox: false,
  },
  {
    name: 'contract_amount',
    displayName: 'Contract $$',
    type: 'number',
    isCheckbox: false,
  },
  {
    name: 'created_date',
    displayName: 'Created',
    type: 'date',
    isCheckbox: false,
  },
  {
    name: 'contract_date',
    displayName: 'Contract ✓',
    type: 'date',
    isCheckbox: false,
  },
  {
    name: 'survey_final_completion_date',
    displayName: 'Site Survey',
    type: 'date',
    isCheckbox: false,
  },
  {
    name: 'ntp_complete_date',
    displayName: 'NTP',
    type: 'date',
    isCheckbox: false,
  },
  {
    name: 'permit_submit_date',
    displayName: 'Perm Submit',
    type: 'date',
    isCheckbox: false,
  },
  {
    name: 'permit_approval_date',
    displayName: 'Perm App',
    type: 'date',
    isCheckbox: false,
  },
  {
    name: 'ic_submit_date',
    displayName: 'IC Sub',
    type: 'date',
    isCheckbox: false,
  },
  {
    name: 'ic_approval_date',
    displayName: 'IC APP',
    type: 'date',
    isCheckbox: false,
  },
  {
    name: 'jeopardy_date',
    displayName: 'Jeopardy',
    type: 'date',
    isCheckbox: false,
  },
];