export default [
    {
      name: 'unique_id',
      displayName: 'Unique ID',
      type: 'string',
      isCheckbox: false,
    },
    {
      name: 'home_owner',
      displayName: 'Home Owner',
      type: 'string',
      isCheckbox: false,
    },
    {
      name: 'current_status',
      displayName: 'Financer',
      type: 'string',
      isCheckbox: false,
    },
    {
      name: 'dealer_code',
      displayName: 'Source',
      type: 'string',
      isCheckbox: false,
    },
    {
      name: 'sys_size',
      displayName: 'Type',
      type: 'number',
      isCheckbox: false,
    },
    {
      name: 'contract',
      displayName: 'Loan Type',
      type: 'number',
      isCheckbox: false,
    },
    {
      name: 'other_adders',
      displayName: 'Street Address',
      type: 'number',
      isCheckbox: false,
    },
    
    {
      name: 'rep_1',
      displayName: 'City',
      type: 'string',
      isCheckbox: false,
    },
    { name: 'rep_2', displayName: 'ST', type: 'string', isCheckbox: false },
    {
      name: 'setter',
      displayName: 'ZIP',
      type: 'string',
      isCheckbox: false,
    },
    {
      name: 'st',
      displayName: 'Email',
      type: 'string',
      isCheckbox: false,
    },
    {
      name: 'contract_date',
      displayName: 'Phone Number',
      type: 'date',
      isCheckbox: false,
    },
    {
      name: 'loan_fee',
      displayName: 'Rep 1',
      type: 'number',
      isCheckbox: false,
    },
    {
      name: 'net_epc',
      displayName: 'Appt Setter',
      type: 'number',
      isCheckbox: false,
    },
    { name: 'credit', displayName: 'Sys. Size', type: 'string', isCheckbox: false },
    {
      name: 'draw_amt',
      displayName: 'Contract $$',
      type: 'number',
      isCheckbox: false,
    },
    { name: 'rl', displayName: 'Created', type: 'number', isCheckbox: false },
   
    {
      name: 'today',
      displayName: 'Contract ✓',
      type: 'date',
      isCheckbox: false,
    },
    { name: 'amount', displayName: 'Site Survey', type: 'number', isCheckbox: false },
    { name: 'epc', displayName: 'NTP', type: 'number', isCheckbox: false },
    {
      name: 'amt_paid',
      displayName: 'Perm Submit',
      type: 'number',
      isCheckbox: false,
    },
    {
      name: 'balance',
      displayName: 'Perm App',
      type: 'number',
      isCheckbox: false,
    },
    { name: 'help', displayName: 'IC Sub', type: 'string', isCheckbox: false },
    { name: 'help', displayName: 'IC APP', type: 'string', isCheckbox: false },
    { name: 'help', displayName: 'Jeopardy', type: 'string', isCheckbox: false },
  ];
  